import "@/styles/globals.css";
import Head from "next/head";
import { Montserrat } from "next/font/google";
import NavBar from "@/components/NavBar";
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Amir Fattahi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-bug.svg" />
      </Head>
      <main
        className={`${montserrat.className} font-mont bg-light w-full min-h-screen`}
      >
        {" "}
        <NavBar />
        <Component {...pageProps} />
      </main>
    </>
  );
}